README.md
Validation will fail if the protected $username variable is not set in the AuthController.
=> small doc tweaks

src/Config/auth.php, tests/AdldapTest.php
The text and the configuration didn't match.
Also it didn't work because `login_attribute` is set to
`samaccountname`.
This pull request changes the default value.
=> Adjust configuration to text

README.md
To only publish `adldap2-laravel` package's configuration files.
=> Add a tag name to the vendor:publish Artisan commands in README.md

composer.json
Update Composer file to remove Laravel as a requirement so that this project can be used with Laravel as well as Lumen (requiring Laravel adds the Laravel framework and removes Illuminate as a requirement, which means Lumen no longer functions).
=> Fix for Lumen

.travis.yml
travis bump to newest version of php. Allows for failures.
=> Add php 7.0 into travis

src/Middleware/WindowsAuthenticate.php
The adds a simple Auth::check() to determine if the user is already authenticated in the session.
=> Prevent re-authentication with every request.

src/AdldapServiceProvider.php
By binding Adldap2 to a common interface shared by both Laravel and Lumen this allows the library to work with Lumen out of the box.
NB. Lumen needs additional configuration with a manually added config file.
=> This allows Adldap2-Laravel to work with Lumen

readme.md
The current link to sync passwords is dead. This commit fixes the issue and corrects the documentation.
=> Fix link to syncing passwords doc in readme

.gitignore
Prevent accidental stage / commit of composer.lock or vendor files.
=> Add composer vendor and composer.lock to gitignore

docs/auth/scopes.md
Fixed a small typo: `accouning` -> `accounting`.
=> Fix small typo

docs/auth/scopes.md
In the comment block, "Builder" was misspelled as "Builer".
=> Fix spelling in scopes.md

src/Commands/Import.php
Right now, if the user tries to run with --no-interaction, the script will not import the users.
With this change, the script will import the users if --no-interaction is specified.
=> Bypass import confirmation with --no-interaction

src/Auth/DatabaseUserProvider.php
The getModel method was missing and caused issues with some additional packages.
=> Update DatbaseUserProvider.php to add missing method

src/Config/config.php
You can set the option auto_connect to true/false from the Laravel .env file with ADLDAP_AUTO_CONNECT=true
=> Can set auto_connect from .env file

composer.json
Thanks to @mazedlx and his pull request #342 Adldap2-Laravel has now Laravel 5.5 package automatic discovery support.
There is just a little error in the configuration, the namespace of the provider is wrong.
My PR fixes that issue.
=> Fix namespace

src/Commands/Import.php
This re-implements #284 (#344) which makes it possible to run `adldap:import` unattended (e.g. cron / scheduler) For some reason the change done in #284 is missing from `v3.0` and `dev-master`
This is for` v3.0` since the importer in `dev-master` has changed (see #435 for that)
=> [v3.0] Allow imports to be done with "no-interaction"

src/Commands/Console/Import.php
This re-implements #284 (#344) which makes it possible to run `adldap:import` unattended (e.g. cron / scheduler) For some reason the change done in #284 is missing from `v3.0` and `dev-master`
=> [Master] Allow imports to be done with "no-interaction"

src/Auth/DatabaseUserProvider.php, src/Commands/Import.php
This fixes #448 where a random password would be generated every import / user login if `password_sync` is disabled. This would result in an unnecessary change to the userdata (and timestamps).
Note: This uses the import command from the `v3.0` branch, which is currently lacking the `no-interaction` fix committed earlier.
=> Fixes #448: Only generate a random password if we don't have one set

src/Listeners/BindsLdapUserModel.php, tests/DatabaseTestCase.php, tests/EloquentAuthenticateTest.php
This new method check wether the Auth provider is an Adldap Provider. This allows you to use the same User model (which uses the `HasLdapUser` trait) with both the `adldap` and `eloquent` driver.
=> Added 'usesAdldapProvider' method to the 'BindsLdapUserModel' listener

src/Config/config.php
With changes in Adldap2 v4.0, the bindAsAdministrator function explicitly uses the admin_account_prefix and admin_account_suffix configuration variables and does not append the normal account prefix/suffix if empty.
=> Clarify documentation on admin prefix/suffix

docs/auth/setup.md
=>  Use Hash::make() instead of bcrypt()

src/Auth/DatabaseUserProvider.php, src/Auth/NoDatabaseUserProvider.php, src/Commands/Console/Import.php, src/Commands/Import.php, src/Middleware/WindowsAuthenticate.php, src/Resolvers/UserResolver.php, src/Validation/Rules/DenyTrashed.php, tests/DatabaseTestCase.php
As of Laravel 5.8, the `Event::fire` method has been officially removed and replaced with `Event::dispatch`.
https://laravel.com/docs/5.8/upgrade#events
This PR adds support for Laravel 5.8, however will mean the minimum supported version will now be 5.4+
If keeping 5.0-5.3 support is imperative, it may be possible to create a function to delegate between `Event::fire` and `Event::dispatch` based upon the value returned from `App::version()`.
=> Fixed removed fire method for event dispatcher

src/Commands/Console/Import.php
The command is currently throwing an exception, if no user were found.
Since this exception is never and can't be catched, the function should rather return an information text instead of throwing this exception.
=> Return console output instead of exception

docs/auth/setup.md
#807 
Updated documentation for deprecated String function.
Still keept the old version but have added comments with version.
=> str_contains deprecated - docs out of date

src/Resolvers/UserResolver.php, tests/DatabaseProviderTest.php, tests/UserResolverTest.php
- Laravel Version: 7.1.3
- Adldap2-Laravel Version: v6.0.9
- PHP Version: 7.4.3
- LDAP Type: OpenLDAP
When trying to authenticate users using the `NoDatabaseUserProvider` the package is not binding to the LDAP server but only trying to search for the specific record:
```
[2020-03-14 15:47:42] local.INFO: LDAP (ldap://openldap:389) - Connection: default - Operation: Search - Base DN: dc=domain,dc=com - Filter: (&(objectclass=inetorgperson)(objectclass=person)(uid=testuser)) - Selected: (*,entryuuid) - Time Elapsed: 0.55
```
However if I use the facade or inject the `AdldapInterface` the package seems to work just fine. The difference that I noticed is that the facade and the injected interface, when calling the `search()` method using the magic `__call` method on the `Adldap` instance, is …
=> Lazy connection before searching for user while trying to authenticate

src/Auth/DatabaseUserProvider.php
When having connection or network failures, the fallback was not executed and the user was unable to login on the application even though the fallback option was enabled.
=> Catch exception and trigger fallback

src/Validation/Rules/DenyTrashed.php
method_exists requires first parameter to be object or string now and won't accept a null parameter
=> Make it work with PHP 8.0
